### ISSUE TITLE
gotoPrevState without arguments raises TypeError: gotoState() argument after ** must be a mapping, not tuple

### ISSUE THREAD

**Issue by Sidney28** [darcato/pysmlib#6]
Hello. 

I faced with a problem with gotoPrevState method of fsmBase class. The following code shell switches from state1 to state2 and back:

```python
from smlib import fsmBase, loader


class TestPreviousStateFsm(fsmBase):

    def __init__(self, name, *args, **kwargs):
        super(TestPreviousStateFsm, self).__init__(name, **kwargs)
        self.gotoState('state1')

    def state1_eval(self):
        self.gotoState('state2')

    def state2_eval(self):
        self.gotoPrevState()


def entry():
    l = loader()
    l.setVerbosity(3)  # DEBUG verbosity
    l.load(TestPreviousStateFsm, "TEST")
    l.start()


if __name__ == '__main__':
    entry()
```

But it raise an TypeError exception:

```
    0.00s: D - TEST[      undefined] : going to state -> state1
    0.00s: D - REPORT[      undefined] : going to state -> run
    0.00s: D - TEST[      undefined] : undefined => state1
    0.00s: D - TEST[         state1] : executing state1_eval()
    0.00s: D - TEST[         state1] : going to state -> state2
    0.00s: D - TEST[         state1] : end of state1_eval()
    0.00s: D - TEST[         state1] : state1 => state2
    0.00s: D - TEST[         state2] : executing state2_eval()
    0.00s: D - REPORT[      undefined] : undefined => run1 fsms started!

    0.00s: D - REPORT[            run] : executing run_entry()
    0.00s: D - REPORT[            run] : set 0 watchdogs
    0.00s: D - REPORT[            run] : executing run_eval()
    0.00s: D - REPORT[            run] : end of run_eval()
    0.00s: D - REPORT[            run] : No events to process going to sleep

Exception in thread TEST:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/smlib/fsm.py", line 181, in run
    self.eval_forever()
  File "/usr/local/lib/python3.8/dist-packages/smlib/fsm.py", line 162, in eval_forever
    changed = self.eval()  # eval viene eseguito senza lock
  File "/usr/local/lib/python3.8/dist-packages/smlib/fsm.py", line 149, in eval
    self._curstate(*self._curstateargs[0], **self._curstateargs[1])
  File "/home/sidney/git.apiisu.ru/taiga-astroclimat/taiga_astroclimat/fsm_for_test.py", line 15, in state2_eval
    self.gotoPrevState()
  File "/usr/local/lib/python3.8/dist-packages/smlib/fsm.py", line 105, in gotoPrevState
    self.gotoState(self._prevstatename, **args)
TypeError: gotoState() argument after ** must be a mapping, not tuple

```

The reason in the  gotoPrevState method in https://github.com/darcato/pysmlib/blob/0cbc7f91367c853d6ed966bb01754d99ebeba15b/smlib/fsm.py#L101

The code:
```python

def gotoPrevState(self, **kwargs) -> None:
        '''Go back to the previous state'''
        if self._prevstatename:
            args = kwargs if kwargs else self._prevstateargs
            self.gotoState(self._prevstatename, **args)

```

Probably it should be rewritten as follow:
```python

def gotoPrevState(self, *args, **kwargs) -> None:
        '''Go back to the previous state'''
        if self._prevstatename:
            if args or kwargs:
                self.gotoState(self._prevstatename, *args, **kwargs)
            else:
                args, kwargs = self._prevstateargs
                self.gotoState(self._prevstatename, *args, **kwargs)

```
Or something like that (I did not test the code yet). If you agree, I can test and prepare a pull request to fix the problem.  Thank you.

**Comment by darcato** [comment]
Yes, I can see the problem. Feel frre to open the PR, thank you.

**Comment by Sidney28** [comment]
Thank you. I checked. It works for me. I have created a PR.
